csrftoken = getCookie('csrftoken')
# Django Cross Site Request Forgery protection via AJAX
# https://docs.djangoproject.com/en/dev/ref/contrib/csrf/#ajax

getCookie = (name) ->
  cookieValue = null
  if document.cookie and document.cookie != ''
    cookies = document.cookie.split(';')
    i = 0
    while i < cookies.length
      cookie = jQuery.trim(cookies[i])
      # Does this cookie string begin with the name we want?
      if cookie.substring(0, name.length + 1) == name + '='
        cookieValue = decodeURIComponent(cookie.substring(name.length + 1))
        break
      i++
  cookieValue

csrfSafeMethod = (method) ->
  # These HTTP methods do not require CSRF protection
  /^(GET|HEAD|OPTIONS|TRACE)$/.test method

$.ajaxSetup beforeSend: (xhr, settings) ->
  if !csrfSafeMethod(settings.type) and !@crossDomain
    xhr.setRequestHeader 'X-CSRFToken', csrftoken
  return

# ---
# generated by js2coffee 2.0.0
