planoutdata:
  image: busybox
  volumes:
    - /var/lib/postgresql/data
    - /data

db:
  image: planout/postgis
  volumes_from:
    - planoutdata

web:
  build:  /opt/planout/
  command: nf start -e envs/.env -j Profile 
  ports:
    - "8001:8000"

  links:
    - db:db
  volumes:
    - .: /opt/planout/
