planoutdata:
  image: busybox
  volumes:
    - /var/lib/postgresql/data
    - /data

redis:
  image: dockerfile/redis

db:
  image: planout/postgis
  volumes_from:
    - planoutdata

web:
  build:  /opt/planout/
  command: nf start -e .env -j Profile 
  ports:
    - "8001:8000"
  links:
    - db:db
    - redis:redis
  volumes:
    - /opt/planout.vn:/code