planoutdata:
  image: busybox
  volumes:
    - /var/lib/postgresql/data
    - /data

redis:
  image: dockerfile/redis

db:
  image: planout/postgis_init
  volumes_from:
    - planoutdata

web:
  build:  /opt/planout/
  command: foreman start
  ports:
    - "8001:8000"
  links:
    - db:db
    - redis:redis
  volumes:
    - /var/www/planout/media:/var/www/planout/media
    - /var/www/planout/public:/var/www/planout/public
