
planoutdata:
  image: busybox
  volumes:
    - /data:/var/lib/postgresql
  expose:
    - 5432

redis:
  image: dockerfile/redis

db:
  image: planout/postgis
  volumes_from:
    - planoutdata

web:
  build: /opt/planout/
  command: foreman start
  ports:
    - "8001:8000"
  links:
    - db:db
    - redis:redis
  volumes:
    - /var/www/planout/media:/var/www/planout/media
    - /var/www/planout/public:/var/www/planout/public